### ISSUE TITLE
Next Release ToDo 

### ISSUE THREAD

**Issue by Webbah** [upb-lea/ElectricGrid.jl#111]
Please make when done, that we can get ready for final release

- [x] Vdc notebook (Marvin, Daniel)
- [x] non-linear notebook (Benedikt)
- [x] GUI (Jan, Joseph)
    - [x] parameter setting send from GUI to backend
    - [x] scale the cable parameters depending on the length of the line in the GUI
    - [x] clickable cables (representation of eq. length km) -> set parameters per km (R, L, ...)

**Comment by MarvinMeyer** [comment]
Testing 

- [ ] @Webbah 
- [ ] @MarvinMeyer 
- [ ] @josephjoseph704 
- [ ] @janstenner 
- [ ] @benebrueck

**Comment by Webbah** [comment]
new PR done for next release
